### ISSUE TITLE
Clases

### ISSUE THREAD

**Issue by cargon86** [UNICAH-ICC-SAP/GestionPracticasWeb#25]
Este módulo gestionará las clases coprogramáticas, considerando clases especiales como inglés y clases del área de la salud.

Las clases tendrán la siguiente nomenclatura con respecto al tipo de clase:

1 --> Clase normal.
2 --> Inglés
3 --> Labotarotorio.
4 --> Coprogramáticas

Requisitos:

- Registro de clases coprogramáticas con su respectivo horario.
- Considerar duración especial para algunas clases (ej. inglés, que se llevan dos horas).

Validaciones:
- Verificar que los horarios no se solapen con otras clases.

Acciones Especiales:
- Evaluación y ajuste de horarios para evitar conflictos.

**Comment by LuisF20** [comment]
Se realizó el cambió solicitado en la tabla "clases".

**Comment by DarponJoscas** [comment]
Se modificaron los modelos de pensum carrera_clase_bloque y clases.
