### ISSUE TITLE
Cargas Académicas

### ISSUE THREAD

**Issue by cargon86** [UNICAH-ICC-SAP/GestionPracticasWeb#30]
Deberá mostrar lo siguiente:

1. La carga académica que tiene cada docente.

**Comment by cargon86** [comment]
En espera de store de redux y endpoints de periodo y detalle_periodo.

**Comment by Kevin504Hn** [comment]
Se implementó el controlador y la ruta para obtener las clases por docente. Además, se crearon las funciones necesarias y se establecieron las relaciones entre las tablas. Esto permite consultar las clases asociadas a cada docente de forma eficiente.

**Comment by cargon86** [comment]
Se implementó la vista usando el endpoint, se imprime en pantalla las secciones por docente.
