### ISSUE TITLE
Mejoras GUI Pensums.

### ISSUE THREAD

**Issue by Acalix-unicah** [UNICAH-ICC-SAP/GestionPracticasWeb#31]
Realizar los ajustes a la visualización del pensum según se solicita en la imagen.

![image](https://github.com/user-attachments/assets/64e59fcb-e526-40de-998f-68b8516218f1)

**Comment by cargon86** [comment]
Ajustes realizados especificados en la imagen.

* UNICAH-ICC-SAP/GestionPracticasApi/issues/10
