### ISSUE TITLE
Listado de docentes no se ve correctamente

### ISSUE THREAD

**Issue by Acalix-unicah** [UNICAH-ICC-SAP/GestionPracticasWeb#32]
Las tablas en el perfil administrador no se muestran paginadas.

![image](https://github.com/user-attachments/assets/43a4a285-2af0-4897-be63-46a26e9a6f43)

**Comment by BryanHHZavala** [comment]
Ya estan corregidas las tablas con el metodo de paginación, se mando en el pr de login
