### ISSUE TITLE
Alumnos

### ISSUE THREAD

**Issue by Acalix-unicah** [UNICAH-ICC-SAP/GestionPracticasWeb#34]
En el perfil del alumno, agregar un apartado para visualizar su terna (con los docentes asignados) y otro para documentación.

**_Criterios de Aceptación:_**

**Visualización de Terna:**

Apartado donde el alumno puede ver su terna y los docentes asignados.

**Apartado de Documentación:**

Incluir un espacio para que el alumno vea la sección de documentación, indicando que está "En Construcción".

Los apartados de terna y documentación son accesibles en el perfil del alumno y funcionan según especificaciones.

**Comment by David-Andino** [comment]
Cambios front

Se creo la página de perfil alumno, agregando una función para mostrar las ternas a las que pertenece donde aparecerán los docentes asignados a dicha terna y otro aparatado para documentación que actualmente se encuentra en desarrollo.
